name: Ensure Node.js compatibility

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
        - 10.0.0
        - 10.1.x
        - 10.2.x
        - 10.3.x
        - 10.4.x
        - 10.5.x
        - 10.6.x
        - 10.7.x
        - 10.8.x
        - 10.9.x
        - 10.10.x
        - 10.11.x
        - 10.12.x
        - 10.13.x
        - 10.14.x
        - 10.15.x
        - 10.16.x
        - 10.17.x
        - 10.18.x
        - 10.19.x
        - 10.20.x
        - 10.21.x
        - 10.22.x
        - 10.23.x
        - 10.24.x
        - 11.1.x
        - 11.2.x
        - 11.3.x
        - 11.4.x
        - 11.5.x
        - 11.6.x
        - 11.7.x
        - 11.8.x
        - 11.9.x
        - 11.10.x
        - 11.11.x
        - 11.12.x
        - 11.13.x
        - 11.14.x
        - 11.15.x
        - 12.0.x
        - 12.1.x
        - 12.2.x
        - 12.3.x
        - 12.4.x
        - 12.5.x
        - 12.6.x
        - 12.7.x
        - 12.8.x
        - 12.9.x
        - 12.10.x
        - 12.11.x
        - 12.12.x
        - 12.13.x
        - 12.14.x
        - 12.15.x
        - 12.16.x
        - 12.17.x
        - 12.18.x
        - 12.19.x
        - 12.20.x
        - 12.21.x
        - 12.22.x
        - 13.0.x
        - 13.1.x
        - 13.2.x
        - 13.3.x
        - 13.4.x
        - 13.5.x
        - 13.6.x
        - 13.7.x
        - 13.8.x
        - 13.9.x
        - 13.10.x
        - 13.11.x
        - 13.12.x
        - 13.13.x
        - 13.14.x
        - 14.0.x
        - 14.1.x
        - 14.2.x
        - 14.3.x
        - 14.4.x
        - 14.5.x
        - 14.6.x
        - 14.7.x
        - 14.8.x
        - 14.9.x
        - 14.10.x
        - 14.11.x
        - 14.12.x
        - 14.13.x
        - 14.14.x
        - 14.15.x
        - 14.16.x
        - 14.17.x
        - 14.18.x
        - 14.19.x
        - 14.20.x
        - 14.21.x
        - 15.0.x
        - 15.1.x
        - 15.2.x
        - 15.3.x
        - 15.4.x
        - 15.5.x
        - 15.6.x
        - 15.7.x
        - 15.8.x
        - 15.9.x
        - 15.10.x
        - 15.11.x
        - 15.12.x
        - 15.13.x
        - 15.14.x
        - 16.0.x
        - 16.1.x
        - 16.2.x
        - 16.3.x
        - 16.4.x
        - 16.5.x
        - 16.6.x
        - 16.7.x
        - 16.8.x
        - 16.9.x
        - 16.10.x
        - 16.11.x
        - 16.12.x
        - 16.13.x
        - 16.14.x
        - 16.15.x
        - 16.16.x
        - 16.17.x
        - 16.18.x
        - 16.19.x
        - 16.20.x
        - 17.0.x
        - 17.1.x
        - 17.2.x
        - 17.3.x
        - 17.4.x
        - 17.5.x
        - 17.6.x
        - 17.7.x
        - 17.8.x
        - 17.9.x
        - 18.0.x
        - 18.1.x
        - 18.2.x
        - 18.3.x
        - 18.4.x
        - 18.5.x
        - 18.6.x
        - 18.7.x
        - 18.8.x
        - 18.9.x
        - 18.10.x
        - 18.11.x
        - 18.12.x
        - 18.13.x
        - 18.14.x
        - 18.15.x
        - 18.16.x
        - 18.17.x
        - 19.0.x
        - 19.1.x
        - 19.2.x
        - 19.3.x
        - 19.4.x
        - 19.5.x
        - 19.6.x
        - 19.7.x
        - 19.8.x
        - 19.9.x
        - 20.0.x
        - 20.1.x
        - 20.2.x
        - 20.3.x
        - 20.4.x
        - 20.5.x

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm test
