name: Ensure consistent coding style and find basic coding errors

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 18
      uses: actions/setup-node@v1
      with:
        node-version: '18'
    - run: npm install
    - run: npm run lint
